/**
 * e2e credentials (Task 7C).
 *
 * The authenticated suites use DEDICATED `e2e-*` admin accounts, provisioned by
 * the API-driven setup project (`tests/e2e/e2e.setup.ts`) against the live
 * server — NOT the demo seed's own accounts. Two reasons:
 *  - the rich-seed role admins (content-editor@…, etc.) are not guaranteed to
 *    exist on every DB, whereas the setup creates the e2e ones idempotently;
 *  - the setup turns the back-office 2FA ON and enrols `e2e-super`, so leaving
 *    the real seeded super-admin (`admin@publicpulse.com.bd`) untouched keeps a
 *    developer's own manual admin login password-only (that account stays
 *    un-enrolled → the `require2FA` gate lets it through without an OTP).
 *
 * The e2e super-admin's TOTP secret is generated by the REAL in-test enrolment
 * flow (the setup drives `/api/2fa/enroll` → `/api/2fa/verify-enroll`) and
 * written to `.fixtures.json`; `readFixtures().superTotpSecret` returns it.
 */

/**
 * A password that satisfies the admin composition policy
 * (`src/auth/validatePassword.ts`): 3 classes (letters, digit, specials),
 * length ≥ 8, no ascending/descending run of 4, and contains none of the
 * `e2e-*` login IDs.
 */
export const E2E_ADMIN_PASSWORD = 'Publicpulse-9-Portal!'

export const E2E_SUPER = {
  email: 'e2e-super@admin.example.com',
  loginId: 'e2e-super',
  password: E2E_ADMIN_PASSWORD,
  roleId: 'ROLE_ADMIN',
}

export const E2E_CONTENT = {
  email: 'e2e-content@admin.example.com',
  loginId: 'e2e-content',
  password: E2E_ADMIN_PASSWORD,
  roleId: 'ROLE_CONTENT_EDITOR',
}

export const E2E_PRIVACY = {
  email: 'e2e-privacy@admin.example.com',
  loginId: 'e2e-privacy',
  password: E2E_ADMIN_PASSWORD,
  roleId: 'ROLE_PRIVACY_OFFICER',
}

export const E2E_STATS = {
  email: 'e2e-stats@admin.example.com',
  loginId: 'e2e-stats',
  password: E2E_ADMIN_PASSWORD,
  roleId: 'ROLE_STATISTICS_ANALYST',
}

/** The real seeded super-admin used ONLY by the setup to provision the rest. */
export const SEED_SUPER = {
  email: process.env.SEED_ADMIN_EMAIL || 'admin@publicpulse.com.bd',
  password: process.env.SEED_ADMIN_PASSWORD || 'changeme-dev-only!',
}

/** The seeded active demo member (public site, no 2FA). */
export const DEMO_MEMBER = {
  identifier: 'member@demo.example.com',
  loginId: 'demo-member',
  password: process.env.SEED_MEMBER_PASSWORD || 'Pulse-Member-2026',
}
