import type { Payload } from 'payload'

import type { SeedStep } from '../types'

/**
 * Example boards seeded on the demo site so Task 3B (posts) and Phase 4
 * (public rendering) have data to work against. Kept as a typed constant so
 * tests assert against the same source of truth.
 *
 * `bbsId` is intentionally omitted — it is auto-generated by `Boards.ts`.
 * `fields`/`listFieldOrder`/`detailFieldOrder` are omitted too, so each board
 * gets the built-in field-grid defaults (`BOARD_DEFAULT_FIELDS`).
 */
export const SEED_BOARDS: {
  name: string
  boardTypeCode: string
  isIntegrated: boolean
  boardForm: 'list' | 'thumbnail'
  attachmentsEnabled: boolean
  headerNotice?: string
}[] = [
  {
    name: 'Notice',
    boardTypeCode: 'PG0001',
    isIntegrated: true,
    boardForm: 'list',
    attachmentsEnabled: true,
    headerNotice: 'This is the Notice board.',
  },
  {
    name: 'Gallery',
    boardTypeCode: 'PG0002',
    isIntegrated: false,
    boardForm: 'thumbnail',
    attachmentsEnabled: true,
  },
]

async function findBoardTypeId(payload: Payload, code: string): Promise<number> {
  const found = await payload.find({
    collection: 'boardTypes',
    where: { code: { equals: code } },
    limit: 1,
    pagination: false,
    overrideAccess: true,
  })
  const doc = found.docs[0]
  if (!doc) {
    // Programmer error: boardTypesStep must run before boardsStep (see
    // src/seed/index.ts) — fail loudly rather than seed a board with a
    // missing type.
    throw new Error(`[seed:boards] board type "${code}" not found — did boardTypesStep run first?`)
  }
  return doc.id
}

/**
 * Seeds example boards on the demo site (ref 1-27/1-33). Idempotent: each
 * board is looked up by (tenant, name) before create. Depends on `sitesStep`
 * (demo site) and `boardTypesStep` (PG0001/PG0002) — see src/seed/index.ts.
 */
export const boardsStep: SeedStep = {
  name: 'boards',
  async run(payload: Payload) {
    const demoSite = await payload.find({
      collection: 'sites',
      where: { siteId: { equals: 'demo' } },
      limit: 1,
      pagination: false,
      overrideAccess: true,
    })
    const demoSiteId = demoSite.docs[0]?.id
    if (demoSiteId === undefined) {
      throw new Error('[seed:boards] demo site not found — did sitesStep run first?')
    }

    for (const board of SEED_BOARDS) {
      const existing = await payload.find({
        collection: 'boards',
        where: { and: [{ tenant: { equals: demoSiteId } }, { name: { equals: board.name } }] },
        limit: 1,
        pagination: false,
        overrideAccess: true,
      })

      if (existing.docs.length > 0) {
        payload.logger.info(`[seed:boards] board "${board.name}" already exists — skipping.`)
        continue
      }

      const boardTypeId = await findBoardTypeId(payload, board.boardTypeCode)

      await payload.create({
        collection: 'boards',
        data: {
          tenant: demoSiteId,
          name: board.name,
          boardType: boardTypeId,
          isIntegrated: board.isIntegrated,
          boardForm: board.boardForm,
          attachmentsEnabled: board.attachmentsEnabled,
          ...(board.headerNotice !== undefined ? { headerNotice: board.headerNotice } : {}),
        },
        overrideAccess: true,
      })
      payload.logger.info(`[seed:boards] created board "${board.name}" on demo site.`)
    }
  },
}
