/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    users: User;
    media: Media;
    sites: Site;
    departments: Department;
    codeClassifications: CodeClassification;
    codeGroups: CodeGroup;
    codes: Code;
    roles: Role;
    adminMenus: AdminMenu;
    passwordPolicies: PasswordPolicy;
    accessLogs: AccessLog;
    loginHistory: LoginHistory;
    permissionChangeLogs: PermissionChangeLog;
    menuPermissionLogs: MenuPermissionLog;
    'payload-kv': PayloadKv;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {
    roles: {
      users: 'users';
    };
  };
  collectionsSelect: {
    users: UsersSelect<false> | UsersSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    sites: SitesSelect<false> | SitesSelect<true>;
    departments: DepartmentsSelect<false> | DepartmentsSelect<true>;
    codeClassifications: CodeClassificationsSelect<false> | CodeClassificationsSelect<true>;
    codeGroups: CodeGroupsSelect<false> | CodeGroupsSelect<true>;
    codes: CodesSelect<false> | CodesSelect<true>;
    roles: RolesSelect<false> | RolesSelect<true>;
    adminMenus: AdminMenusSelect<false> | AdminMenusSelect<true>;
    passwordPolicies: PasswordPoliciesSelect<false> | PasswordPoliciesSelect<true>;
    accessLogs: AccessLogsSelect<false> | AccessLogsSelect<true>;
    loginHistory: LoginHistorySelect<false> | LoginHistorySelect<true>;
    permissionChangeLogs: PermissionChangeLogsSelect<false> | PermissionChangeLogsSelect<true>;
    menuPermissionLogs: MenuPermissionLogsSelect<false> | MenuPermissionLogsSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: number;
  };
  fallbackLocale: null;
  globals: {};
  globalsSelect: {};
  locale: null;
  widgets: {
    collections: CollectionsWidget;
  };
  user: User;
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: number;
  /**
   * Legacy login ID (ref 1-15/1-16 "ID"). Distinct from the email used for authentication; shown in the account list and used by ID/PW recovery. Optional here — self-service applicants supply it via the account-request form.
   */
  loginId?: string | null;
  /**
   * Display name (legacy 관리자 이름).
   */
  name?: string | null;
  /**
   * Account lifecycle. Only "Active" accounts may log in. Approve a pending account by switching to Active; a dormant account is reactivated the same way.
   */
  status: 'pending' | 'active' | 'dormant' | 'locked';
  /**
   * Roles held by this admin. Effective menu access is the union of every held role's grants, or unconditional if any held role has isSuper checked. Changing this field always requires the system.admins grant, even when editing your own account.
   */
  roles?: (number | Role)[] | null;
  /**
   * Department this admin belongs to (legacy 부서, picked from the tree).
   */
  department?: (number | null) | Department;
  /**
   * Duties/role description (legacy 업무내용) — shown in the org chart later.
   */
  duties?: string | null;
  /**
   * Mobile phone number (legacy 휴대전화).
   */
  mobile?: string | null;
  /**
   * Internal extension (legacy 내선번호).
   */
  extension?: string | null;
  /**
   * Profile photo (legacy 프로필 사진; jpg/jpeg/png/gif, displayed 64×64).
   */
  profilePhoto?: (number | null) | Media;
  /**
   * Last successful login. Maintained by the system; used by the dormancy sweep.
   */
  lastLoginAt?: string | null;
  totpSecret?: string | null;
  /**
   * Whether Google-OTP two-factor authentication is set up and confirmed for this account.
   */
  totpConfirmed?: boolean | null;
  /**
   * When two-factor authentication was confirmed. Null until first enrolment.
   */
  totpEnrolledAt?: string | null;
  /**
   * Consecutive failed OTP codes. Resets on a successful code.
   */
  totpFailedAttempts?: number | null;
  /**
   * When set to a future time, the OTP step is locked out (too many failed codes). Auto-clears on expiry / a successful code.
   */
  totpLockUntil?: string | null;
  /**
   * Admin action: clear this user’s 2FA enrolment so they must set up a new device on next login. The user is emailed. Requires the system.admins grant.
   */
  resetTwoFactorDevice?: boolean | null;
  /**
   * Admin action: regenerate this user’s OTP secret (invalidates the old code immediately; user re-enrols with a new QR). The user is emailed. Requires the system.admins grant.
   */
  regenerateTwoFactorSecret?: boolean | null;
  tenants?:
    | {
        tenant: number | Site;
        id?: string | null;
      }[]
    | null;
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
  collection: 'users';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "roles".
 */
export interface Role {
  id: number;
  /**
   * e.g. "ROLE_ADMIN". Uppercase letters, digits, and underscores only.
   */
  roleId: string;
  name: string;
  description: string;
  /**
   * Super roles bypass all menu permission checks.
   */
  isSuper?: boolean | null;
  /**
   * Admin menus this role grants access to. Ignored for a role with isSuper checked (super roles bypass this entirely).
   */
  menuGrants?: (number | AdminMenu)[] | null;
  /**
   * Users holding this role (read-only — ref 1-12 "role users view").
   */
  users?: {
    docs?: (number | User)[];
    hasNextPage?: boolean;
    totalDocs?: number;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "adminMenus".
 */
export interface AdminMenu {
  id: number;
  /**
   * PERMANENT permission key, dot-path convention (e.g. "system.sites"). Every gated collection checks against this exact string — do not rename after roles have been granted this menu.
   */
  menuKey: string;
  name: string;
  /**
   * Parent menu node. Leave empty for a top-level (1-depth) menu.
   */
  parent?: (number | null) | AdminMenu;
  /**
   * Sibling display order (lower first).
   */
  order?: number | null;
  /**
   * The Payload collection slug this menu node gates, if any (e.g. "sites"). Leave empty for a pure grouping/parent node with no directly bound collection.
   */
  collectionSlug?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "departments".
 */
export interface Department {
  id: number;
  /**
   * Department name (legacy 부서명).
   */
  name: string;
  /**
   * Department duties/notes (legacy 부서업무).
   */
  duties?: string | null;
  phone?: string | null;
  fax?: string | null;
  /**
   * Legacy 사용여부. Inactive departments are hidden from pickers but kept (not deleted), so historical references keep resolving.
   */
  isActive?: boolean | null;
  /**
   * Parent department. Leave empty for a top-level department.
   */
  parent?: (number | null) | Department;
  /**
   * Sibling display order (lower first).
   */
  order?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: number;
  alt: string;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "sites".
 */
export interface Site {
  id: number;
  /**
   * Lowercase alphanumeric identifier, e.g. "bos" or "demo".
   */
  siteId: string;
  name: string;
  /**
   * Full URL starting with http:// or https://
   */
  url: string;
  /**
   * Marks this site as the admin back-office (legacy "bos") rather than a user-facing site.
   */
  isAdminSite?: boolean | null;
  satisfactionEnabled?: boolean | null;
  dataManagerEnabled?: boolean | null;
  /**
   * Web accessibility validation usage (operates only in local/dev environments per legacy behavior).
   */
  accessibilityValidation?: ('off' | 'popup' | 'db' | 'popup_db') | null;
  /**
   * Require a Google OTP code after login for this admin site.
   */
  twoFactorEnabled?: boolean | null;
  /**
   * Allow admin account applications from the login page for this admin site.
   */
  accountApplicationEnabled?: boolean | null;
  /**
   * Homepage logo. Allowed types: jpg, jpeg, png, gif.
   */
  logo?: (number | null) | Media;
  footer?: {
    orgName?: {
      value?: string | null;
      show?: boolean | null;
    };
    addressPostalCode?: {
      value?: string | null;
      show?: boolean | null;
    };
    addressLine1?: {
      value?: string | null;
      show?: boolean | null;
    };
    addressLine2?: {
      value?: string | null;
      show?: boolean | null;
    };
    phone?: {
      value?: string | null;
      show?: boolean | null;
    };
    fax?: {
      value?: string | null;
      show?: boolean | null;
    };
    copyright?: {
      value?: string | null;
      show?: boolean | null;
    };
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "codeClassifications".
 */
export interface CodeClassification {
  id: number;
  /**
   * English-letters-only classification code, e.g. "SYS". One per sub-system.
   */
  code: string;
  name: string;
  description?: string | null;
  isActive?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "codeGroups".
 */
export interface CodeGroup {
  id: number;
  /**
   * Uppercase snake_case, matching the DB column name this code group backs, e.g. "APRV_CD".
   */
  codeId: string;
  name: string;
  classification: number | CodeClassification;
  description?: string | null;
  isActive?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "codes".
 */
export interface Code {
  id: number;
  group: number | CodeGroup;
  /**
   * Concatenated 2-digit-per-depth value, e.g. "01", "0101", "010101". Must start with the parent code, if any.
   */
  code: string;
  name: string;
  /**
   * Parent detail code. Leave empty for a top-level (depth 1) code.
   */
  parent?: (number | null) | Code;
  /**
   * Computed automatically: 1 for a top-level code, otherwise parent depth + 1.
   */
  depth?: number | null;
  /**
   * Sibling display order (lower first).
   */
  order?: number | null;
  description?: string | null;
  /**
   * Optional legacy code value from U-CMS v3.0 (e.g. "Y"/"I"/"N", "AVU001"), kept for audit parity.
   */
  legacyValue?: string | null;
  isActive?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "passwordPolicies".
 */
export interface PasswordPolicy {
  id: number;
  /**
   * Human-readable password rule shown to users (legacy 비밀번호 규칙). Note: this text is informational — enforcement is fixed in code (src/auth/validatePassword.ts).
   */
  ruleText: string;
  /**
   * Legacy 사용여부. The most recently created policy among those marked active is the one displayed to users.
   */
  isActive?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "accessLogs".
 */
export interface AccessLog {
  id: number;
  /**
   * The acting admin (null for anonymous/system events).
   */
  actor?: (number | null) | User;
  /**
   * Denormalized "name(id)" snapshot — survives deletion of the user.
   */
  actorLabel?: string | null;
  /**
   * The adminMenu menuKey touched, if any.
   */
  menuKey?: string | null;
  menuLabel?: string | null;
  action: 'login' | 'logout' | 'list' | 'view' | 'create' | 'update' | 'delete';
  url: string;
  /**
   * Raw client IP (IPv4/IPv6), captured as-is.
   */
  ipAddress?: string | null;
  /**
   * The session's login timestamp, for session reconstruction.
   */
  sessionLoginAt?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "loginHistory".
 */
export interface LoginHistory {
  id: number;
  /**
   * The user display name (legacy 이름). Masked in the list view.
   */
  userLabel?: string | null;
  /**
   * The attempted/real login identifier (legacy 아이디). Masked in the list view.
   */
  loginId?: string | null;
  /**
   * Whether the login succeeded (legacy 로그인 성공여부). Failure view filters on false.
   */
  success?: boolean | null;
  /**
   * Reason a failed login was rejected, if known.
   */
  failReason?: string | null;
  /**
   * Raw client IP (IPv4/IPv6), captured as-is.
   */
  ipAddress?: string | null;
  /**
   * Geo-IP overseas flag (legacy 해외여부). Default domestic until a GeoIP provider is wired.
   */
  isOverseas?: boolean | null;
  /**
   * Mobile-device flag (legacy 모바일여부), from User-Agent parsing.
   */
  isMobile?: boolean | null;
  userAgent?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "permissionChangeLogs".
 */
export interface PermissionChangeLog {
  id: number;
  /**
   * The user whose roles changed (legacy 이름).
   */
  targetUserLabel?: string | null;
  targetUserId?: string | null;
  /**
   * The affected user’s email (legacy 이메일주소).
   */
  targetUserEmail?: string | null;
  /**
   * e.g. "roles: [ROLE_AA] → [ROLE_AA, ROLE_BB]" (legacy 권한변경 요약).
   */
  changeSummary?: string | null;
  /**
   * Who made the change (legacy 변경자).
   */
  actorLabel?: string | null;
  /**
   * The actor’s IP (legacy 변경IP).
   */
  ipAddress?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "menuPermissionLogs".
 */
export interface MenuPermissionLog {
  id: number;
  /**
   * The role whose menu grants changed (legacy 권한명).
   */
  roleLabel?: string | null;
  /**
   * The role code (legacy 권한코드), e.g. "ROLE_CC".
   */
  roleId?: string | null;
  /**
   * Menu labels granted in this event (legacy 메뉴 권한 등록).
   */
  addedMenus?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  /**
   * Menu labels revoked in this event (legacy 메뉴 권한 제거).
   */
  removedMenus?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  /**
   * Actor-label snapshot of users in the role at change time (legacy 소속 사용자).
   */
  roleMemberSnapshot?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  /**
   * Who made the change (legacy 변경자).
   */
  actorLabel?: string | null;
  /**
   * The actor’s IP (legacy 변경IP).
   */
  ipAddress?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: number;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: number;
  document?:
    | ({
        relationTo: 'users';
        value: number | User;
      } | null)
    | ({
        relationTo: 'media';
        value: number | Media;
      } | null)
    | ({
        relationTo: 'sites';
        value: number | Site;
      } | null)
    | ({
        relationTo: 'departments';
        value: number | Department;
      } | null)
    | ({
        relationTo: 'codeClassifications';
        value: number | CodeClassification;
      } | null)
    | ({
        relationTo: 'codeGroups';
        value: number | CodeGroup;
      } | null)
    | ({
        relationTo: 'codes';
        value: number | Code;
      } | null)
    | ({
        relationTo: 'roles';
        value: number | Role;
      } | null)
    | ({
        relationTo: 'adminMenus';
        value: number | AdminMenu;
      } | null)
    | ({
        relationTo: 'passwordPolicies';
        value: number | PasswordPolicy;
      } | null)
    | ({
        relationTo: 'accessLogs';
        value: number | AccessLog;
      } | null)
    | ({
        relationTo: 'loginHistory';
        value: number | LoginHistory;
      } | null)
    | ({
        relationTo: 'permissionChangeLogs';
        value: number | PermissionChangeLog;
      } | null)
    | ({
        relationTo: 'menuPermissionLogs';
        value: number | MenuPermissionLog;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: number;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: number;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  loginId?: T;
  name?: T;
  status?: T;
  roles?: T;
  department?: T;
  duties?: T;
  mobile?: T;
  extension?: T;
  profilePhoto?: T;
  lastLoginAt?: T;
  totpSecret?: T;
  totpConfirmed?: T;
  totpEnrolledAt?: T;
  totpFailedAttempts?: T;
  totpLockUntil?: T;
  resetTwoFactorDevice?: T;
  regenerateTwoFactorSecret?: T;
  tenants?:
    | T
    | {
        tenant?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  alt?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "sites_select".
 */
export interface SitesSelect<T extends boolean = true> {
  siteId?: T;
  name?: T;
  url?: T;
  isAdminSite?: T;
  satisfactionEnabled?: T;
  dataManagerEnabled?: T;
  accessibilityValidation?: T;
  twoFactorEnabled?: T;
  accountApplicationEnabled?: T;
  logo?: T;
  footer?:
    | T
    | {
        orgName?:
          | T
          | {
              value?: T;
              show?: T;
            };
        addressPostalCode?:
          | T
          | {
              value?: T;
              show?: T;
            };
        addressLine1?:
          | T
          | {
              value?: T;
              show?: T;
            };
        addressLine2?:
          | T
          | {
              value?: T;
              show?: T;
            };
        phone?:
          | T
          | {
              value?: T;
              show?: T;
            };
        fax?:
          | T
          | {
              value?: T;
              show?: T;
            };
        copyright?:
          | T
          | {
              value?: T;
              show?: T;
            };
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "departments_select".
 */
export interface DepartmentsSelect<T extends boolean = true> {
  name?: T;
  duties?: T;
  phone?: T;
  fax?: T;
  isActive?: T;
  parent?: T;
  order?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "codeClassifications_select".
 */
export interface CodeClassificationsSelect<T extends boolean = true> {
  code?: T;
  name?: T;
  description?: T;
  isActive?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "codeGroups_select".
 */
export interface CodeGroupsSelect<T extends boolean = true> {
  codeId?: T;
  name?: T;
  classification?: T;
  description?: T;
  isActive?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "codes_select".
 */
export interface CodesSelect<T extends boolean = true> {
  group?: T;
  code?: T;
  name?: T;
  parent?: T;
  depth?: T;
  order?: T;
  description?: T;
  legacyValue?: T;
  isActive?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "roles_select".
 */
export interface RolesSelect<T extends boolean = true> {
  roleId?: T;
  name?: T;
  description?: T;
  isSuper?: T;
  menuGrants?: T;
  users?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "adminMenus_select".
 */
export interface AdminMenusSelect<T extends boolean = true> {
  menuKey?: T;
  name?: T;
  parent?: T;
  order?: T;
  collectionSlug?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "passwordPolicies_select".
 */
export interface PasswordPoliciesSelect<T extends boolean = true> {
  ruleText?: T;
  isActive?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "accessLogs_select".
 */
export interface AccessLogsSelect<T extends boolean = true> {
  actor?: T;
  actorLabel?: T;
  menuKey?: T;
  menuLabel?: T;
  action?: T;
  url?: T;
  ipAddress?: T;
  sessionLoginAt?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "loginHistory_select".
 */
export interface LoginHistorySelect<T extends boolean = true> {
  userLabel?: T;
  loginId?: T;
  success?: T;
  failReason?: T;
  ipAddress?: T;
  isOverseas?: T;
  isMobile?: T;
  userAgent?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "permissionChangeLogs_select".
 */
export interface PermissionChangeLogsSelect<T extends boolean = true> {
  targetUserLabel?: T;
  targetUserId?: T;
  targetUserEmail?: T;
  changeSummary?: T;
  actorLabel?: T;
  ipAddress?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "menuPermissionLogs_select".
 */
export interface MenuPermissionLogsSelect<T extends boolean = true> {
  roleLabel?: T;
  roleId?: T;
  addedMenus?: T;
  removedMenus?: T;
  roleMemberSnapshot?: T;
  actorLabel?: T;
  ipAddress?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "collections_widget".
 */
export interface CollectionsWidget {
  data?: {
    [k: string]: unknown;
  };
  width: 'full';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}