/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
    members: MemberAuthOperations;
  };
  blocks: {};
  collections: {
    users: User;
    media: Media;
    attachments: Attachment;
    sites: Site;
    departments: Department;
    codeClassifications: CodeClassification;
    codeGroups: CodeGroup;
    codes: Code;
    boardTypes: BoardType;
    boards: Board;
    posts: Post;
    profanityWords: ProfanityWord;
    memberBannedWords: MemberBannedWord;
    members: Member;
    notificationAreas: NotificationArea;
    popups: Popup;
    banners: Banner;
    adminNotices: AdminNotice;
    guideMenus: GuideMenu;
    menus: Menu;
    webContents: WebContent;
    termsDocuments: TermsDocument;
    shortUrls: ShortUrl;
    helpEntries: HelpEntry;
    surveys: Survey;
    surveyQuestions: SurveyQuestion;
    surveyResponses: SurveyResponse;
    satisfactionRatings: SatisfactionRating;
    pageViews: PageView;
    trafficDaily: TrafficDaily;
    roles: Role;
    adminMenus: AdminMenu;
    passwordPolicies: PasswordPolicy;
    adminIpRules: AdminIpRule;
    accessLogs: AccessLog;
    loginHistory: LoginHistory;
    permissionChangeLogs: PermissionChangeLog;
    menuPermissionLogs: MenuPermissionLog;
    personalInfoAccessLogs: PersonalInfoAccessLog;
    errorLogs: ErrorLog;
    'payload-kv': PayloadKv;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {
    roles: {
      users: 'users';
    };
  };
  collectionsSelect: {
    users: UsersSelect<false> | UsersSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    attachments: AttachmentsSelect<false> | AttachmentsSelect<true>;
    sites: SitesSelect<false> | SitesSelect<true>;
    departments: DepartmentsSelect<false> | DepartmentsSelect<true>;
    codeClassifications: CodeClassificationsSelect<false> | CodeClassificationsSelect<true>;
    codeGroups: CodeGroupsSelect<false> | CodeGroupsSelect<true>;
    codes: CodesSelect<false> | CodesSelect<true>;
    boardTypes: BoardTypesSelect<false> | BoardTypesSelect<true>;
    boards: BoardsSelect<false> | BoardsSelect<true>;
    posts: PostsSelect<false> | PostsSelect<true>;
    profanityWords: ProfanityWordsSelect<false> | ProfanityWordsSelect<true>;
    memberBannedWords: MemberBannedWordsSelect<false> | MemberBannedWordsSelect<true>;
    members: MembersSelect<false> | MembersSelect<true>;
    notificationAreas: NotificationAreasSelect<false> | NotificationAreasSelect<true>;
    popups: PopupsSelect<false> | PopupsSelect<true>;
    banners: BannersSelect<false> | BannersSelect<true>;
    adminNotices: AdminNoticesSelect<false> | AdminNoticesSelect<true>;
    guideMenus: GuideMenusSelect<false> | GuideMenusSelect<true>;
    menus: MenusSelect<false> | MenusSelect<true>;
    webContents: WebContentsSelect<false> | WebContentsSelect<true>;
    termsDocuments: TermsDocumentsSelect<false> | TermsDocumentsSelect<true>;
    shortUrls: ShortUrlsSelect<false> | ShortUrlsSelect<true>;
    helpEntries: HelpEntriesSelect<false> | HelpEntriesSelect<true>;
    surveys: SurveysSelect<false> | SurveysSelect<true>;
    surveyQuestions: SurveyQuestionsSelect<false> | SurveyQuestionsSelect<true>;
    surveyResponses: SurveyResponsesSelect<false> | SurveyResponsesSelect<true>;
    satisfactionRatings: SatisfactionRatingsSelect<false> | SatisfactionRatingsSelect<true>;
    pageViews: PageViewsSelect<false> | PageViewsSelect<true>;
    trafficDaily: TrafficDailySelect<false> | TrafficDailySelect<true>;
    roles: RolesSelect<false> | RolesSelect<true>;
    adminMenus: AdminMenusSelect<false> | AdminMenusSelect<true>;
    passwordPolicies: PasswordPoliciesSelect<false> | PasswordPoliciesSelect<true>;
    adminIpRules: AdminIpRulesSelect<false> | AdminIpRulesSelect<true>;
    accessLogs: AccessLogsSelect<false> | AccessLogsSelect<true>;
    loginHistory: LoginHistorySelect<false> | LoginHistorySelect<true>;
    permissionChangeLogs: PermissionChangeLogsSelect<false> | PermissionChangeLogsSelect<true>;
    menuPermissionLogs: MenuPermissionLogsSelect<false> | MenuPermissionLogsSelect<true>;
    personalInfoAccessLogs: PersonalInfoAccessLogsSelect<false> | PersonalInfoAccessLogsSelect<true>;
    errorLogs: ErrorLogsSelect<false> | ErrorLogsSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: number;
  };
  fallbackLocale: null;
  globals: {};
  globalsSelect: {};
  locale: null;
  widgets: {
    collections: CollectionsWidget;
  };
  user: User | Member;
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
export interface MemberAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: number;
  /**
   * Legacy login ID (ref 1-15/1-16 "ID"). Distinct from the email used for authentication; shown in the account list and used by ID/PW recovery. Optional here — self-service applicants supply it via the account-request form.
   */
  loginId?: string | null;
  /**
   * Display name (legacy 관리자 이름).
   */
  name?: string | null;
  /**
   * Account lifecycle. Only "Active" accounts may log in. Approve a pending account by switching to Active; a dormant account is reactivated the same way.
   */
  status: 'pending' | 'active' | 'dormant' | 'locked';
  /**
   * Roles held by this admin. Effective menu access is the union of every held role's grants, or unconditional if any held role has isSuper checked. Changing this field always requires the system.admins grant, even when editing your own account.
   */
  roles?: (number | Role)[] | null;
  /**
   * Department this admin belongs to (legacy 부서, picked from the tree).
   */
  department?: (number | null) | Department;
  /**
   * Duties/role description (legacy 업무내용) — shown in the org chart later.
   */
  duties?: string | null;
  /**
   * Mobile phone number (legacy 휴대전화).
   */
  mobile?: string | null;
  /**
   * Internal extension (legacy 내선번호).
   */
  extension?: string | null;
  /**
   * Profile photo (legacy 프로필 사진; jpg/jpeg/png/gif, displayed 64×64).
   */
  profilePhoto?: (number | null) | Media;
  /**
   * Last successful login. Maintained by the system; used by the dormancy sweep.
   */
  lastLoginAt?: string | null;
  totpSecret?: string | null;
  /**
   * Whether Google-OTP two-factor authentication is set up and confirmed for this account.
   */
  totpConfirmed?: boolean | null;
  /**
   * When two-factor authentication was confirmed. Null until first enrolment.
   */
  totpEnrolledAt?: string | null;
  /**
   * Consecutive failed OTP codes. Resets on a successful code.
   */
  totpFailedAttempts?: number | null;
  /**
   * When set to a future time, the OTP step is locked out (too many failed codes). Auto-clears on expiry / a successful code.
   */
  totpLockUntil?: string | null;
  /**
   * Admin action: clear this user’s 2FA enrolment so they must set up a new device on next login. The user is emailed. Requires the system.admins grant.
   */
  resetTwoFactorDevice?: boolean | null;
  /**
   * Admin action: regenerate this user’s OTP secret (invalidates the old code immediately; user re-enrols with a new QR). The user is emailed. Requires the system.admins grant.
   */
  regenerateTwoFactorSecret?: boolean | null;
  tenants?:
    | {
        tenant: number | Site;
        id?: string | null;
      }[]
    | null;
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
  collection: 'users';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "roles".
 */
export interface Role {
  id: number;
  /**
   * e.g. "ROLE_ADMIN". Uppercase letters, digits, and underscores only.
   */
  roleId: string;
  name: string;
  description: string;
  /**
   * Super roles bypass all menu permission checks.
   */
  isSuper?: boolean | null;
  /**
   * Admin menus this role grants access to. Ignored for a role with isSuper checked (super roles bypass this entirely).
   */
  menuGrants?: (number | AdminMenu)[] | null;
  /**
   * Users holding this role (read-only — ref 1-12 "role users view").
   */
  users?: {
    docs?: (number | User)[];
    hasNextPage?: boolean;
    totalDocs?: number;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "adminMenus".
 */
export interface AdminMenu {
  id: number;
  /**
   * PERMANENT permission key, dot-path convention (e.g. "system.sites"). Every gated collection checks against this exact string — do not rename after roles have been granted this menu.
   */
  menuKey: string;
  name: string;
  /**
   * Parent menu node. Leave empty for a top-level (1-depth) menu.
   */
  parent?: (number | null) | AdminMenu;
  /**
   * Sibling display order (lower first).
   */
  order?: number | null;
  /**
   * The Payload collection slug this menu node gates, if any (e.g. "sites"). Leave empty for a pure grouping/parent node with no directly bound collection.
   */
  collectionSlug?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "departments".
 */
export interface Department {
  id: number;
  /**
   * Department name (legacy 부서명).
   */
  name: string;
  /**
   * Department duties/notes (legacy 부서업무).
   */
  duties?: string | null;
  phone?: string | null;
  fax?: string | null;
  /**
   * Legacy 사용여부. Inactive departments are hidden from pickers but kept (not deleted), so historical references keep resolving.
   */
  isActive?: boolean | null;
  /**
   * Parent department. Leave empty for a top-level department.
   */
  parent?: (number | null) | Department;
  /**
   * Sibling display order (lower first).
   */
  order?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: number;
  alt: string;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "sites".
 */
export interface Site {
  id: number;
  /**
   * Lowercase alphanumeric identifier, e.g. "bos" or "demo".
   */
  siteId: string;
  name: string;
  /**
   * Full URL starting with http:// or https://
   */
  url: string;
  /**
   * Marks this site as the admin back-office (legacy "bos") rather than a user-facing site.
   */
  isAdminSite?: boolean | null;
  satisfactionEnabled?: boolean | null;
  dataManagerEnabled?: boolean | null;
  /**
   * Require administrator approval before a newly signed-up member can log in.
   */
  memberApprovalRequired?: boolean | null;
  /**
   * Web accessibility validation usage (operates only in local/dev environments per legacy behavior).
   */
  accessibilityValidation?: ('off' | 'popup' | 'db' | 'popup_db') | null;
  /**
   * Require a Google OTP code after login for this admin site.
   */
  twoFactorEnabled?: boolean | null;
  /**
   * Allow admin account applications from the login page for this admin site.
   */
  accountApplicationEnabled?: boolean | null;
  /**
   * Homepage logo. Allowed types: jpg, jpeg, png, gif.
   */
  logo?: (number | null) | Media;
  footer?: {
    orgName?: {
      value?: string | null;
      show?: boolean | null;
    };
    addressPostalCode?: {
      value?: string | null;
      show?: boolean | null;
    };
    addressLine1?: {
      value?: string | null;
      show?: boolean | null;
    };
    addressLine2?: {
      value?: string | null;
      show?: boolean | null;
    };
    phone?: {
      value?: string | null;
      show?: boolean | null;
    };
    fax?: {
      value?: string | null;
      show?: boolean | null;
    };
    copyright?: {
      value?: string | null;
      show?: boolean | null;
    };
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "attachments".
 */
export interface Attachment {
  id: number;
  tenant?: (number | null) | Site;
  alt?: string | null;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "codeClassifications".
 */
export interface CodeClassification {
  id: number;
  /**
   * English-letters-only classification code, e.g. "SYS". One per sub-system.
   */
  code: string;
  name: string;
  description?: string | null;
  isActive?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "codeGroups".
 */
export interface CodeGroup {
  id: number;
  /**
   * Uppercase snake_case, matching the DB column name this code group backs, e.g. "APRV_CD".
   */
  codeId: string;
  name: string;
  classification: number | CodeClassification;
  description?: string | null;
  isActive?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "codes".
 */
export interface Code {
  id: number;
  group: number | CodeGroup;
  /**
   * Concatenated 2-digit-per-depth value, e.g. "01", "0101", "010101". Must start with the parent code, if any.
   */
  code: string;
  name: string;
  /**
   * Parent detail code. Leave empty for a top-level (depth 1) code.
   */
  parent?: (number | null) | Code;
  /**
   * Computed automatically: 1 for a top-level code, otherwise parent depth + 1.
   */
  depth?: number | null;
  /**
   * Sibling display order (lower first).
   */
  order?: number | null;
  description?: string | null;
  /**
   * Optional legacy code value from U-CMS v3.0 (e.g. "Y"/"I"/"N", "AVU001"), kept for audit parity.
   */
  legacyValue?: string | null;
  isActive?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "boardTypes".
 */
export interface BoardType {
  id: number;
  /**
   * System-assigned board type code (PGxxxx), auto-generated on create — not user-editable.
   */
  code?: string | null;
  name: string;
  /**
   * Behavioral kind — drives post rendering/behavior in Task 3B (integrated/photo/qna/faq/attachment/extended).
   */
  kind: 'integrated' | 'photo' | 'qna' | 'faq' | 'attachment' | 'extended';
  /**
   * Informational: legacy stored every board type in one physical table (tb_bbs). The rebuild likewise stores every board type in the single `posts` collection — this field is retained for legacy/audit parity and is not a live table switch.
   */
  tableName?: string | null;
  /**
   * Board type detail (게시판유형상세). Max 800 characters.
   */
  description?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "boards".
 */
export interface Board {
  id: number;
  tenant?: (number | null) | Site;
  /**
   * System-assigned board ID (Bxxxxxxx), auto-generated on create.
   */
  bbsId?: string | null;
  name: string;
  /**
   * Privacy §3 security-document library (ref 3-4). Gated on Privacy · Security Documents instead of Board Management.
   */
  securityDoc?: boolean | null;
  /**
   * The board's type (from Board Type Management). Locked to the integrated type when Integrated board is checked.
   */
  boardType: number | BoardType;
  /**
   * Integrated board — locks board type to PG0001 and skin to common (ref 1-27).
   */
  isIntegrated?: boolean | null;
  /**
   * Skin choice only. React rendering resolves this in Phase 4 (legacy JSP path mapping deferred).
   */
  skin?: ('common' | 'site') | null;
  /**
   * Board form — list or thumbnail (gallery) layout (ref 1-28 callout 4).
   */
  boardForm?: ('list' | 'thumbnail') | null;
  sortOrder?: ('latest' | 'oldest') | null;
  /**
   * Rich-text editor is available to admins only; end users never get it (ref 1-28).
   */
  editorForAdminOnly?: boolean | null;
  commentsEnabled?: boolean | null;
  prevNextEnabled?: boolean | null;
  excelExport?: boolean | null;
  userPostAllowed?: boolean | null;
  /**
   * Allow public/private (secret) posts (공개/비공개, ref 1-28).
   */
  secretPostAllowed?: boolean | null;
  /**
   * Days a post shows the New icon after registration (ref 1-28 New icon toggle).
   */
  newIconWindow?: number | null;
  listCount?: number | null;
  pageCount?: number | null;
  /**
   * Raw HTML rendered above the board. Sanitize on render in Phase 4 (XSS).
   */
  topContent?: string | null;
  /**
   * Raw HTML rendered below the board. Sanitize on render in Phase 4 (XSS).
   */
  bottomContent?: string | null;
  /**
   * Configurable notice banner shown at the top of the board (ref 2-7).
   */
  headerNotice?: string | null;
  attachmentsEnabled?: boolean | null;
  attachmentMaxCount?: number | null;
  /**
   * 10 MByte recommended (legacy hint).
   */
  attachmentMaxSizeMB?: number | null;
  /**
   * Lowercase, comma-separated, no spaces — e.g. "hwp,pdf,png".
   */
  attachmentAllowedExtensions?: string | null;
  /**
   * Up to 3 classification-code bindings. Each binds a pre-existing code GROUP (분류코드) — see report for the codeGroups-vs-codes decision.
   */
  categories?:
    | {
        /**
         * The bound classification code group (must pre-exist in Code Management — popup selection only in legacy).
         */
        classificationCode: number | CodeGroup;
        /**
         * Display label for this category.
         */
        title?: string | null;
        /**
         * Value for the HTML title attribute.
         */
        htmlTitleAttr?: string | null;
        /**
         * Injected HTML attributes, e.g. data="12".
         */
        attributeValue?: string | null;
        /**
         * Inline CSS for the rendered input.
         */
        style?: string | null;
        useFlag?: boolean | null;
        requiredFlag?: boolean | null;
        listFlag?: boolean | null;
        detailFlag?: boolean | null;
        searchFlag?: boolean | null;
        id?: string | null;
      }[]
    | null;
  /**
   * Per-field config for every post column. Defaults to the built-in fields + extraField1-4 (varchar) + extraContent1-4 (text). Drives the posts schema in Task 3B.
   */
  fields?:
    | {
        /**
         * Stable key, e.g. 'title', 'extraField1'.
         */
        fieldKey: string;
        label?: string | null;
        htmlTitleAttr?: string | null;
        /**
         * e.g. data="12".
         */
        attributeValue?: string | null;
        style?: string | null;
        /**
         * HTML input element the field renders as (ref 1-30 Type selector).
         */
        inputType?: ('text' | 'textarea' | 'date' | 'email' | 'select' | 'number') | null;
        useFlag?: boolean | null;
        requiredFlag?: boolean | null;
        listFlag?: boolean | null;
        detailFlag?: boolean | null;
        searchFlag?: boolean | null;
        id?: string | null;
      }[]
    | null;
  /**
   * Ordered fieldKeys for the LIST view columns (ref 1-31). Drag-drop UI is later.
   */
  listFieldOrder?: string[] | null;
  /**
   * Ordered fieldKeys for the DETAIL view (ref 1-32). Independent of list order.
   */
  detailFieldOrder?: string[] | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "posts".
 */
export interface Post {
  id: number;
  tenant?: (number | null) | Site;
  /**
   * The board this post belongs to — determines the post's config/kind.
   */
  board: number | Board;
  /**
   * Denormalized board kind (auto-set from the board's type on save).
   */
  boardKind?: string | null;
  /**
   * Denormalized security-document flag (auto-set from the post's board on save).
   */
  securityDoc?: boolean | null;
  title: string;
  /**
   * Display name of the author (legacy stored a free-text name).
   */
  author?: string | null;
  /**
   * The admin/user who authored this post, if applicable.
   */
  authorUser?: (number | null) | User;
  department?: (number | null) | Department;
  team?: string | null;
  /**
   * Post body (Editor mode). HTML/TEXT input modes + sanitize-on-render are a Phase-4 concern.
   */
  content?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  /**
   * Read count; incremented on detail view in Phase 4.
   */
  viewCount?: number | null;
  /**
   * Pinned notice post (공지). Optionally scoped to a date range below.
   */
  isNotice?: boolean | null;
  noticeFrom?: string | null;
  noticeTo?: string | null;
  /**
   * Secret (비공개) post — only its author + admins may view it.
   */
  isSecret?: boolean | null;
  /**
   * Category 1 value — a detail code from the group bound to the board's category slot 1.
   */
  category1?: (number | null) | Code;
  /**
   * Category 2 value — a detail code from the group bound to the board's category slot 2.
   */
  category2?: (number | null) | Code;
  /**
   * Category 3 value — a detail code from the group bound to the board's category slot 3.
   */
  category3?: (number | null) | Code;
  extraField1?: string | null;
  extraField2?: string | null;
  extraField3?: string | null;
  extraField4?: string | null;
  extraContent1?: string | null;
  extraContent2?: string | null;
  extraContent3?: string | null;
  extraContent4?: string | null;
  /**
   * Uploaded files. Constraints (count/size/extensions) come from the board; download via the managed endpoint (/api/files/download).
   */
  attachments?:
    | {
        media: number | Attachment;
        description?: string | null;
        /**
         * The gallery thumbnail (photo boards). At most one per post.
         */
        isRepresentative?: boolean | null;
        /**
         * Per-post file sequence, auto-assigned.
         */
        fileSn?: number | null;
        /**
         * Managed-download counter (see fileDownload.ts).
         */
        downloadCount?: number | null;
        id?: string | null;
      }[]
    | null;
  /**
   * Admin's answer to a Q&A question. Presence sets isAnswered.
   */
  answer?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  /**
   * Auto-stamped to the admin who wrote the answer.
   */
  answeredBy?: (number | null) | User;
  /**
   * Auto-stamped when the answer was written.
   */
  answeredAt?: string | null;
  /**
   * Derived: true once an answer is present.
   */
  isAnswered?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "profanityWords".
 */
export interface ProfanityWord {
  id: number;
  /**
   * A forbidden word. Matching is case-insensitive substring.
   */
  word: string;
  /**
   * Only active words are enforced against new posts.
   */
  isActive?: boolean | null;
  /**
   * The admin who registered this word (auto-set on create).
   */
  registrant?: (number | null) | User;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "memberBannedWords".
 */
export interface MemberBannedWord {
  id: number;
  /**
   * A banned word. Matching is case-insensitive substring.
   */
  word: string;
  /**
   * Where the word is banned: common (everywhere), loginId, or password (ref 1-41).
   */
  scope: 'common' | 'loginId' | 'password';
  /**
   * Only active words are enforced at signup.
   */
  isActive?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "members".
 */
export interface Member {
  id: number;
  /**
   * Public-site login ID (unique per site).
   */
  loginId: string;
  /**
   * Display name / nickname. Member-editable.
   */
  name: string;
  /**
   * Mobile phone number (optional). Member-editable.
   */
  mobile?: string | null;
  /**
   * Membership lifecycle. Only "Active" members may log in.
   */
  status: 'active' | 'pending' | 'dormant' | 'withdrawn';
  /**
   * The site (tenant) this member belongs to.
   */
  tenant: number | Site;
  /**
   * Optional opt-in to marketing messages. Member-editable.
   */
  marketingConsent?: boolean | null;
  /**
   * Snapshot of the terms this member accepted at sign-up (category + version + timestamp). Retained as consent evidence; not member-editable.
   */
  termsConsents?:
    | {
        category: 'service' | 'privacy';
        version: string;
        agreedAt: string;
        id?: string | null;
      }[]
    | null;
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  password?: string | null;
  collection: 'members';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "notificationAreas".
 */
export interface NotificationArea {
  id: number;
  tenant?: (number | null) | Site;
  /**
   * Display image (uploads to Media). Recommended size 490 x 245 px; allowed types jpg/jpeg/png/gif (legacy note).
   */
  image: number | Media;
  title: string;
  linkType?: ('internal' | 'external') | null;
  /**
   * Internal site-relative link — a path like /bos/… or a ?menuSn=… reference (no external URLs or schemes). The menu/program picker popup is deferred to Phase 4 — a text path is stored for now.
   */
  linkInternal?: string | null;
  /**
   * External URL — must start with http:// or https://.
   */
  linkExternal?: string | null;
  /**
   * Link mode (링크 방식): open in a new window (새창/Y) vs the current page (N).
   */
  newWindow?: boolean | null;
  /**
   * Use/expose toggle (사용여부). Inactive items remain in the admin list but never render. Inline list toggling is a Phase-4 UI concern.
   */
  active?: boolean | null;
  /**
   * Exposure start (hour precision). Empty = no lower bound.
   */
  exposeFrom?: string | null;
  /**
   * Exposure end (hour precision). Empty = no upper bound. Outside the window the item is not live.
   */
  exposeTo?: string | null;
  /**
   * Exposure order (노출순서) — lower shows first. The 4-way drag UI is deferred to Phase 4.
   */
  displayOrder?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "popups".
 */
export interface Popup {
  id: number;
  tenant?: (number | null) | Site;
  /**
   * Display image (uploads to Media). Recommended size 160 x 140 px; allowed types jpg/jpeg/png/gif (legacy note).
   */
  image: number | Media;
  title: string;
  linkType?: ('internal' | 'external') | null;
  /**
   * Internal site-relative link — a path like /bos/… or a ?menuSn=… reference (no external URLs or schemes). The menu/program picker popup is deferred to Phase 4 — a text path is stored for now.
   */
  linkInternal?: string | null;
  /**
   * External URL — must start with http:// or https://.
   */
  linkExternal?: string | null;
  /**
   * Use/expose toggle (사용여부). Inactive items remain in the admin list but never render. Inline list toggling is a Phase-4 UI concern.
   */
  active?: boolean | null;
  /**
   * Exposure start (hour precision). Empty = no lower bound.
   */
  exposeFrom?: string | null;
  /**
   * Exposure end (hour precision). Empty = no upper bound. Outside the window the item is not live.
   */
  exposeTo?: string | null;
  /**
   * Width (넓이) in px (popup window geometry, ref 1-48).
   */
  width?: number | null;
  /**
   * Height (높이) in px (popup window geometry, ref 1-48).
   */
  height?: number | null;
  /**
   * Top position (팝업위치 TOP) in px (popup window geometry, ref 1-48).
   */
  top?: number | null;
  /**
   * Left position (팝업위치 LEFT) in px (popup window geometry, ref 1-48).
   */
  left?: number | null;
  /**
   * Scrollbar use (스크롤사용여부) — whether the popup window shows scrollbars.
   */
  showScrollbar?: boolean | null;
  /**
   * Close-for-a-day (하루닫기) — lets a viewer suppress the popup for one day (cookie behavior; frontend concern, the flag is stored here).
   */
  closeForDay?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "banners".
 */
export interface Banner {
  id: number;
  tenant?: (number | null) | Site;
  /**
   * Display image (uploads to Media). Recommended size 196 x 70 px; allowed types jpg/jpeg/png/gif (legacy note).
   */
  image: number | Media;
  /**
   * Representative banner file (대표 배너파일) — the primary banner for the site.
   */
  isRepresentative?: boolean | null;
  title: string;
  linkType?: ('internal' | 'external') | null;
  /**
   * Internal site-relative link — a path like /bos/… or a ?menuSn=… reference (no external URLs or schemes). The menu/program picker popup is deferred to Phase 4 — a text path is stored for now.
   */
  linkInternal?: string | null;
  /**
   * External URL — must start with http:// or https://.
   */
  linkExternal?: string | null;
  /**
   * Link mode (링크 방식): open in a new window (새창/Y) vs the current page (N).
   */
  newWindow?: boolean | null;
  /**
   * Use/expose toggle (사용여부). Inactive items remain in the admin list but never render. Inline list toggling is a Phase-4 UI concern.
   */
  active?: boolean | null;
  /**
   * Exposure start (hour precision). Empty = no lower bound.
   */
  exposeFrom?: string | null;
  /**
   * Exposure end (hour precision). Empty = no upper bound. Outside the window the item is not live.
   */
  exposeTo?: string | null;
  /**
   * Exposure order (노출순서) — lower shows first. The 4-way drag UI is deferred to Phase 4.
   */
  displayOrder?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "adminNotices".
 */
export interface AdminNotice {
  id: number;
  tenant?: (number | null) | Site;
  /**
   * Pinned notices sort above general ones (ref 1-49).
   */
  noticeType: 'pinned' | 'general';
  /**
   * Pin-period start — applies only to pinned notices (ref 1-50 callout 1).
   */
  pinFrom?: string | null;
  /**
   * Pin-period end — applies only to pinned notices.
   */
  pinTo?: string | null;
  title: string;
  department?: (number | null) | Department;
  /**
   * Team name (팀명).
   */
  team?: string | null;
  /**
   * Author display name (작성자).
   */
  author?: string | null;
  /**
   * Notice body (Editor mode). HTML/TEXT input modes + sanitize-on-render are a Phase-4 concern (as with posts).
   */
  content?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  /**
   * Up to 5 image files (png/gif/jpg), each with an optional description (ref 1-50).
   */
  attachments?:
    | {
        media: number | Attachment;
        /**
         * Attachment description (첨부파일 설명).
         */
        description?: string | null;
        id?: string | null;
      }[]
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "guideMenus".
 */
export interface GuideMenu {
  id: number;
  tenant?: (number | null) | Site;
  /**
   * Which utility bar this menu appears in (max 5 for top, ref 1-53).
   */
  position: 'top' | 'bottom';
  /**
   * Menu name (메뉴명).
   */
  name: string;
  linkType?: ('internal' | 'external') | null;
  /**
   * Internal site-relative link — a path like /bos/… or a ?menuSn=… reference (no external URLs or schemes). The menu/program picker popup is deferred to Phase 4 — a text path is stored for now.
   */
  linkInternal?: string | null;
  /**
   * External URL — must start with http:// or https://.
   */
  linkExternal?: string | null;
  /**
   * Link mode (링크 방식): open in a new window (새창/Y) vs the current page (N).
   */
  newWindow?: boolean | null;
  /**
   * Exposure order (노출순서) — lower shows first. The 4-way drag UI is deferred to Phase 4.
   */
  displayOrder?: number | null;
  /**
   * Use/expose toggle (사용여부). Inactive items remain in the admin list but never render. Inline list toggling is a Phase-4 UI concern.
   */
  active?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "menus".
 */
export interface Menu {
  id: number;
  tenant?: (number | null) | Site;
  name: string;
  /**
   * System-assigned per-site menu number (legacy menuSn), used in public URLs. Unique within a site.
   */
  menuNumber?: number | null;
  /**
   * Parent menu (same site). Leave empty for a top-level menu.
   */
  parent?: (number | null) | Menu;
  /**
   * Sibling display order (lower first).
   */
  order?: number | null;
  /**
   * What this menu points at (ref 1-44). Drives which fields below apply.
   */
  contentType?: ('placeholder' | 'program' | 'board' | 'content' | 'link') | null;
  /**
   * The board this menu opens (when content type is Board).
   */
  board?: (number | null) | Board;
  /**
   * Site-relative path (/bos/… or ?menuSn=…) or an absolute http(s) URL (when content type is Link).
   */
  linkUrl?: string | null;
  /**
   * Open the target in a new window (링크 방식: 새창).
   */
  newWindow?: boolean | null;
  /**
   * Active (사용). Inactive menus are hidden from the public nav (shown red in the admin tree — Phase-4 UI).
   */
  active?: boolean | null;
  /**
   * Data manager (담당자) — a user or department. Surfaces on the PUBLIC site only when the site’s dataManagerEnabled toggle is on (Phase 1 sites).
   */
  personInCharge?:
    | ({
        relationTo: 'users';
        value: number | User;
      } | null)
    | ({
        relationTo: 'departments';
        value: number | Department;
      } | null);
  /**
   * Menu visibility by session state (ref 2-13 노출조건).
   */
  exposureCondition?: ('always' | 'loggedInOnly' | 'loggedOutOnly') | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "webContents".
 */
export interface WebContent {
  id: number;
  tenant?: (number | null) | Site;
  /**
   * The menu this content is bound to (1:1). Content exists only for a created menu (ref 2-2).
   */
  menu: number | Menu;
  /**
   * Internal name (legacy 컨텐츠명).
   */
  name?: string | null;
  /**
   * Display title of the page.
   */
  title?: string | null;
  /**
   * The page body. Versioned — every save creates a new version; the published version is the active one.
   */
  content?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  /**
   * Responsible department (담당부서, optional — ref 2-2).
   */
  responsibleDept?: (number | null) | Department;
  /**
   * Responsible person (담당자, optional — ref 2-2).
   */
  responsiblePerson?: string | null;
  /**
   * Informational only — legacy served content via a controller URL; the rebuild renders in Phase 4.
   */
  contentUrl?: string | null;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "termsDocuments".
 */
export interface TermsDocument {
  id: number;
  tenant?: (number | null) | Site;
  /**
   * One of the five fixed legacy terms categories (ref 2-14). Unique per site.
   */
  category: 'termsOfUse' | 'personalInfoProcessing' | 'thirdPartyProvision' | 'uniqueIdCollection' | 'other';
  /**
   * Optional site menu this terms document is surfaced under (ref 2-15). Must belong to the same site.
   */
  menu?: (number | null) | Menu;
  /**
   * Display title of the terms document.
   */
  title: string;
  /**
   * The terms body. Versioned — every save creates a new version; the published version is the active one shown publicly.
   */
  content: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  };
  /**
   * The date this version takes effect (shown in the public change history, ref 2-16).
   */
  effectiveDate?: string | null;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "shortUrls".
 */
export interface ShortUrl {
  id: number;
  tenant?: (number | null) | Site;
  /**
   * Display name (링크명).
   */
  linkName: string;
  /**
   * The destination the short link redirects to (absolute http(s) URL or /path).
   */
  originalUrl: string;
  /**
   * Optional notes (비고).
   */
  remarks?: string | null;
  /**
   * Auto-generated globally-unique short code (used in /s/:code).
   */
  code?: string | null;
  /**
   * Best-effort redirect hit counter.
   */
  hitCount?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "helpEntries".
 */
export interface HelpEntry {
  id: number;
  name: string;
  /**
   * Parent help node. Leave empty for a top-level entry.
   */
  parent?: (number | null) | HelpEntry;
  /**
   * Sibling display order (lower first).
   */
  order?: number | null;
  /**
   * The help body shown by the ⓘ button.
   */
  content?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  /**
   * How this help is matched to a screen. Menu binding wins over service when both match (ref 1-80).
   */
  bindType?: ('service' | 'menu') | null;
  /**
   * Screen URL to match (when Service). Supports a "*" wildcard, e.g. /bos/board/*.
   */
  urlPattern?: string | null;
  /**
   * The menu number to bind to (when Menu) — matched against the current menu.
   */
  menuNumber?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "surveys".
 */
export interface Survey {
  id: number;
  tenant?: (number | null) | Site;
  title: string;
  /**
   * Intro/description shown above the survey (rendered via the safe serializer).
   */
  description?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  /**
   * Owning department (person-in-charge context, ref 2-9).
   */
  department?: (number | null) | Department;
  /**
   * Contact phone for enquiries (ref 2-9).
   */
  contactPhone?: string | null;
  /**
   * Survey topic/category (ref 2-9).
   */
  topic?: string | null;
  /**
   * Survey opens at this time. Leave empty for a draft (questions stay editable).
   */
  openFrom?: string | null;
  /**
   * Survey closes at this time. Empty means no upper bound.
   */
  openTo?: string | null;
  /**
   * Master on/off toggle. An inactive survey is always Closed.
   */
  isActive?: boolean | null;
  /**
   * Derived lifecycle: scheduled | open | closed (from the window + Active toggle).
   */
  status?: string | null;
  /**
   * Who may respond. Members-only surveys require a public-site login.
   */
  audience: 'anyone' | 'members';
  /**
   * When aggregate results are viewable on the public site (ref 2-12).
   */
  resultVisibility: 'afterClose' | 'duringAndAfter' | 'adminsOnly';
  /**
   * Responses are not tied to a member identity (respondent stored as null). One-response is still deduped by a hashed key.
   */
  anonymous?: boolean | null;
  /**
   * True once the first response has been recorded.
   */
  hasResponses?: boolean | null;
  /**
   * Sticky start latch — set once the survey opens or gets its first response, never cleared. Freezes the questions.
   */
  startedAt?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "surveyQuestions".
 */
export interface SurveyQuestion {
  id: number;
  tenant?: (number | null) | Site;
  survey: number | Survey;
  /**
   * Display/ask order (lower first).
   */
  order?: number | null;
  text: string;
  type: 'single' | 'multi' | 'text' | 'textarea';
  required?: boolean | null;
  /**
   * Show this question’s verbatim free-text/"Other" answers in PUBLIC results. Off by default (privacy); the admin export always includes them.
   */
  includeInPublicResults?: boolean | null;
  /**
   * Choices for single/multi questions. An "Other" option renders a free-text box.
   */
  options?:
    | {
        label: string;
        /**
         * Stored value for this option (unique within the question).
         */
        value: string;
        order?: number | null;
        /**
         * Renders an extra free-text input; its text is required when chosen.
         */
        isOther?: boolean | null;
        /**
         * Skip logic (single-choice only, ref 2-11): jump to the question with this order when chosen.
         */
        nextQuestionOrder?: number | null;
        id?: string | null;
      }[]
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "surveyResponses".
 */
export interface SurveyResponse {
  id: number;
  tenant?: (number | null) | Site;
  survey: number | Survey;
  /**
   * The member who responded, or null (anonymous survey/submitter).
   */
  respondent?: (number | null) | Member;
  /**
   * Server-stamped submission time.
   */
  submittedAt?: string | null;
  /**
   * Server-only HMAC dedup key (never read back). Identity-free — enforces one-response without storing who.
   */
  participantKey?: string | null;
  answers?:
    | {
        question: number | SurveyQuestion;
        /**
         * Selected option value(s) for single/multi questions.
         */
        optionValues?: string[] | null;
        /**
         * Free text for text/textarea questions and "other" options.
         */
        textValue?: string | null;
        id?: string | null;
      }[]
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "satisfactionRatings".
 */
export interface SatisfactionRating {
  id: number;
  tenant?: (number | null) | Site;
  /**
   * The rated page menu (per-menu satisfaction dimension, ref 2-19), or null.
   */
  menu?: (number | null) | Menu;
  /**
   * The rated public page path (server-forced).
   */
  pageKey: string;
  /**
   * 5-point satisfaction score (1-5, server-validated).
   */
  score: number;
  /**
   * The member who rated, or null (anonymous).
   */
  member?: (number | null) | Member;
  /**
   * Server-stamped submission time.
   */
  submittedAt?: string | null;
  /**
   * Server-only salted dedup hash (never read back) — stores NO raw IP.
   */
  ipHash?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pageViews".
 */
export interface PageView {
  id: number;
  tenant?: (number | null) | Site;
  /**
   * Captured public path (query string stripped).
   */
  path: string;
  /**
   * The owning menu (resolved for /page/{menuNumber} paths), or null.
   */
  menu?: (number | null) | Menu;
  /**
   * Coarse device class from the UA.
   */
  deviceType?: ('mobile' | 'desktop') | null;
  /**
   * Coarse OS family derived from the UA (no version — privacy-safe).
   */
  osFamily?: ('windows' | 'macos' | 'ios' | 'android' | 'linux' | 'other') | null;
  /**
   * Coarse browser family derived from the UA (no version — privacy-safe).
   */
  browserFamily?: ('chrome' | 'safari' | 'firefox' | 'edge' | 'opera' | 'samsung' | 'ie' | 'other') | null;
  /**
   * Referrer HOST only (never the full referring URL).
   */
  referrerHost?: string | null;
  /**
   * Server-only rotating salted hash — stores NO PII.
   */
  sessionKey?: string | null;
  /**
   * Server-stamped view time.
   */
  ts: string;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "trafficDaily".
 */
export interface TrafficDaily {
  id: number;
  tenant?: (number | null) | Site;
  /**
   * UTC calendar day (YYYY-MM-DD) this rollup covers.
   */
  date: string;
  /**
   * Total page views on this site this day.
   */
  totalViews: number;
  /**
   * Distinct daily session hashes this day (session rotates daily — monthly unique = Σ daily).
   */
  uniqueVisitors: number;
  /**
   * Path/menu breakdown: [{ path, menuNumber, views }] (Menu/Page tab).
   */
  byPath?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  /**
   * OS-family breakdown: [{ key, views }] (OS tab).
   */
  byOs?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  /**
   * Browser-family breakdown: [{ key, views }] (Browser tab).
   */
  byBrowser?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  /**
   * Device-class breakdown: [{ key, views }] (Device tab).
   */
  byDevice?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "passwordPolicies".
 */
export interface PasswordPolicy {
  id: number;
  /**
   * Human-readable password rule shown to users (legacy 비밀번호 규칙). Note: this text is informational — enforcement is fixed in code (src/auth/validatePassword.ts).
   */
  ruleText: string;
  /**
   * Legacy 사용여부. The most recently created policy among those marked active is the one displayed to users.
   */
  isActive?: boolean | null;
  /**
   * Who created this policy version (legacy version-history attribution). A denormalized name(loginId) snapshot, stamped by the system on create; not editable.
   */
  createdBy?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Default-deny admin IP allowlist. While NO rules exist the admin stays open (bootstrap safety); once any rule exists, only IPs matched by an active in-window "allow" rule may reach the admin, and any matching "block" rule wins. Recovery: set ADMIN_IP_ENFORCEMENT=off.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "adminIpRules".
 */
export interface AdminIpRule {
  id: number;
  /**
   * Who requested this access rule (legacy 신청자).
   */
  applicantName: string;
  /**
   * Applicant’s organization/department (legacy 소속).
   */
  affiliation: string;
  /**
   * Applicant’s contact number (legacy 연락처).
   */
  phone: string;
  /**
   * Optional note about this rule (legacy 비고).
   */
  memo?: string | null;
  /**
   * Exact IPv4/IPv6, an IPv4 trailing wildcard (e.g. "192.168.0.*", "10.*"), or "*". WARNING: a bare "*" matches ALL IPs — an active "*" allow rule disables IP restriction entirely.
   */
  ipAddress: string;
  /**
   * Allow-list (default) or explicit block. Under default-deny, "block" wins over any "allow" match.
   */
  accessType: 'allow' | 'block';
  /**
   * Rule takes effect from this date/time (legacy 시작일).
   */
  validFrom: string;
  /**
   * Rule expires after this date/time (legacy 종료일). Expired rules stop matching automatically — no cron needed.
   */
  validTo: string;
  /**
   * Inactive rules are ignored by the guard.
   */
  isActive?: boolean | null;
  /**
   * Which admin site this rule guards (defaults to the admin back-office).
   */
  siteId: number | Site;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "accessLogs".
 */
export interface AccessLog {
  id: number;
  /**
   * The acting admin (null for anonymous/system events).
   */
  actor?: (number | null) | User;
  /**
   * Denormalized "name(id)" snapshot — survives deletion of the user.
   */
  actorLabel?: string | null;
  /**
   * The adminMenu menuKey touched, if any.
   */
  menuKey?: string | null;
  menuLabel?: string | null;
  action: 'login' | 'logout' | 'list' | 'view' | 'create' | 'update' | 'delete' | 'denied';
  url: string;
  /**
   * Raw client IP (IPv4/IPv6), captured as-is.
   */
  ipAddress?: string | null;
  /**
   * The session's login timestamp, for session reconstruction.
   */
  sessionLoginAt?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "loginHistory".
 */
export interface LoginHistory {
  id: number;
  /**
   * The user display name (legacy 이름). Masked in the list view.
   */
  userLabel?: string | null;
  /**
   * The attempted/real login identifier (legacy 아이디). Masked in the list view.
   */
  loginId?: string | null;
  /**
   * Whether the login succeeded (legacy 로그인 성공여부). Failure view filters on false.
   */
  success?: boolean | null;
  /**
   * Reason a failed login was rejected, if known.
   */
  failReason?: string | null;
  /**
   * Raw client IP (IPv4/IPv6), captured as-is.
   */
  ipAddress?: string | null;
  /**
   * Geo-IP overseas flag (legacy 해외여부). Default domestic until a GeoIP provider is wired.
   */
  isOverseas?: boolean | null;
  /**
   * Mobile-device flag (legacy 모바일여부), from User-Agent parsing.
   */
  isMobile?: boolean | null;
  userAgent?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "permissionChangeLogs".
 */
export interface PermissionChangeLog {
  id: number;
  /**
   * The user whose roles changed (legacy 이름).
   */
  targetUserLabel?: string | null;
  targetUserId?: string | null;
  /**
   * The affected user’s email (legacy 이메일주소).
   */
  targetUserEmail?: string | null;
  /**
   * e.g. "roles: [ROLE_AA] → [ROLE_AA, ROLE_BB]" (legacy 권한변경 요약).
   */
  changeSummary?: string | null;
  /**
   * Who made the change (legacy 변경자).
   */
  actorLabel?: string | null;
  /**
   * The actor’s IP (legacy 변경IP).
   */
  ipAddress?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "menuPermissionLogs".
 */
export interface MenuPermissionLog {
  id: number;
  /**
   * The role whose menu grants changed (legacy 권한명).
   */
  roleLabel?: string | null;
  /**
   * The role code (legacy 권한코드), e.g. "ROLE_CC".
   */
  roleId?: string | null;
  /**
   * Menu labels granted in this event (legacy 메뉴 권한 등록).
   */
  addedMenus?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  /**
   * Menu labels revoked in this event (legacy 메뉴 권한 제거).
   */
  removedMenus?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  /**
   * Actor-label snapshot of users in the role at change time (legacy 소속 사용자).
   */
  roleMemberSnapshot?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  /**
   * Who made the change (legacy 변경자).
   */
  actorLabel?: string | null;
  /**
   * The actor’s IP (legacy 변경IP).
   */
  ipAddress?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "personalInfoAccessLogs".
 */
export interface PersonalInfoAccessLog {
  id: number;
  /**
   * When the personal-info access occurred (열람일시).
   */
  occurredAt: string;
  /**
   * Which admin screen produced the access (화면명, e.g. "member-detail").
   */
  screen?: string | null;
  /**
   * Denormalized "name(loginId)" of the member whose PII was accessed. Masked in the list.
   */
  subjectLabel?: string | null;
  /**
   * The member id as TEXT (NOT an FK — see the deadlock note).
   */
  subjectMemberId?: string | null;
  /**
   * The member's site (tenant) id as text — per-site segmentation.
   */
  subjectSiteId?: string | null;
  /**
   * The full request URL/path (including the target member id).
   */
  url: string;
  action: 'view' | 'edit' | 'export';
  /**
   * View-purpose category (열람목적구분).
   */
  purposeCategory: 'view' | 'edit' | 'export' | 'inquiry_response' | 'complaint_handling' | 'other';
  /**
   * Free-text reason (열람목적). REQUIRED for an export (the purpose modal) — the immutable evidence of why the PII was accessed.
   */
  purposeDetail?: string | null;
  /**
   * Denormalized "name(loginId)" of the admin who accessed the PII. Masked in the list.
   */
  viewerLabel?: string | null;
  /**
   * The acting admin id as TEXT (NOT an FK — see the deadlock note).
   */
  viewerId?: string | null;
  /**
   * Raw client IP (IPv4/IPv6), captured as-is from the request (열람IP). Masked in the list.
   */
  ipAddress?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "errorLogs".
 */
export interface ErrorLog {
  id: number;
  /**
   * When the exception occurred (the period-tab axis).
   */
  occurredAt: string;
  /**
   * The exception class name (the by-type stat tab).
   */
  exceptionClass?: string | null;
  /**
   * SANITIZED error message (secrets/PII redacted before storage).
   */
  message?: string | null;
  /**
   * The request URL/path where the error occurred (the by-URL stat tab).
   */
  url?: string | null;
  /**
   * The HTTP method of the failing request, if known.
   */
  httpMethod?: string | null;
  /**
   * The HTTP status returned (>= 500 = captured unhandled exception).
   */
  statusCode?: number | null;
  /**
   * Denormalized "name(id)" of the acting admin (null for anonymous). Masked in the list.
   */
  actorLabel?: string | null;
  /**
   * The acting admin id as text (NOT an FK — see the deadlock note).
   */
  actorId?: string | null;
  /**
   * Raw client IP (IPv4/IPv6), captured as-is from the trusted request.
   */
  ipAddress?: string | null;
  /**
   * Truncated + SANITIZED stack (top frames only; no full internals/secrets).
   */
  stackDigest?: string | null;
  /**
   * Coarse OS/browser family (no version — never fingerprints).
   */
  userAgentFamily?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: number;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: number;
  document?:
    | ({
        relationTo: 'users';
        value: number | User;
      } | null)
    | ({
        relationTo: 'media';
        value: number | Media;
      } | null)
    | ({
        relationTo: 'attachments';
        value: number | Attachment;
      } | null)
    | ({
        relationTo: 'sites';
        value: number | Site;
      } | null)
    | ({
        relationTo: 'departments';
        value: number | Department;
      } | null)
    | ({
        relationTo: 'codeClassifications';
        value: number | CodeClassification;
      } | null)
    | ({
        relationTo: 'codeGroups';
        value: number | CodeGroup;
      } | null)
    | ({
        relationTo: 'codes';
        value: number | Code;
      } | null)
    | ({
        relationTo: 'boardTypes';
        value: number | BoardType;
      } | null)
    | ({
        relationTo: 'boards';
        value: number | Board;
      } | null)
    | ({
        relationTo: 'posts';
        value: number | Post;
      } | null)
    | ({
        relationTo: 'profanityWords';
        value: number | ProfanityWord;
      } | null)
    | ({
        relationTo: 'memberBannedWords';
        value: number | MemberBannedWord;
      } | null)
    | ({
        relationTo: 'members';
        value: number | Member;
      } | null)
    | ({
        relationTo: 'notificationAreas';
        value: number | NotificationArea;
      } | null)
    | ({
        relationTo: 'popups';
        value: number | Popup;
      } | null)
    | ({
        relationTo: 'banners';
        value: number | Banner;
      } | null)
    | ({
        relationTo: 'adminNotices';
        value: number | AdminNotice;
      } | null)
    | ({
        relationTo: 'guideMenus';
        value: number | GuideMenu;
      } | null)
    | ({
        relationTo: 'menus';
        value: number | Menu;
      } | null)
    | ({
        relationTo: 'webContents';
        value: number | WebContent;
      } | null)
    | ({
        relationTo: 'termsDocuments';
        value: number | TermsDocument;
      } | null)
    | ({
        relationTo: 'shortUrls';
        value: number | ShortUrl;
      } | null)
    | ({
        relationTo: 'helpEntries';
        value: number | HelpEntry;
      } | null)
    | ({
        relationTo: 'surveys';
        value: number | Survey;
      } | null)
    | ({
        relationTo: 'surveyQuestions';
        value: number | SurveyQuestion;
      } | null)
    | ({
        relationTo: 'surveyResponses';
        value: number | SurveyResponse;
      } | null)
    | ({
        relationTo: 'satisfactionRatings';
        value: number | SatisfactionRating;
      } | null)
    | ({
        relationTo: 'pageViews';
        value: number | PageView;
      } | null)
    | ({
        relationTo: 'trafficDaily';
        value: number | TrafficDaily;
      } | null)
    | ({
        relationTo: 'roles';
        value: number | Role;
      } | null)
    | ({
        relationTo: 'adminMenus';
        value: number | AdminMenu;
      } | null)
    | ({
        relationTo: 'passwordPolicies';
        value: number | PasswordPolicy;
      } | null)
    | ({
        relationTo: 'adminIpRules';
        value: number | AdminIpRule;
      } | null)
    | ({
        relationTo: 'accessLogs';
        value: number | AccessLog;
      } | null)
    | ({
        relationTo: 'loginHistory';
        value: number | LoginHistory;
      } | null)
    | ({
        relationTo: 'permissionChangeLogs';
        value: number | PermissionChangeLog;
      } | null)
    | ({
        relationTo: 'menuPermissionLogs';
        value: number | MenuPermissionLog;
      } | null)
    | ({
        relationTo: 'personalInfoAccessLogs';
        value: number | PersonalInfoAccessLog;
      } | null)
    | ({
        relationTo: 'errorLogs';
        value: number | ErrorLog;
      } | null);
  globalSlug?: string | null;
  user:
    | {
        relationTo: 'users';
        value: number | User;
      }
    | {
        relationTo: 'members';
        value: number | Member;
      };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: number;
  user:
    | {
        relationTo: 'users';
        value: number | User;
      }
    | {
        relationTo: 'members';
        value: number | Member;
      };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: number;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  loginId?: T;
  name?: T;
  status?: T;
  roles?: T;
  department?: T;
  duties?: T;
  mobile?: T;
  extension?: T;
  profilePhoto?: T;
  lastLoginAt?: T;
  totpSecret?: T;
  totpConfirmed?: T;
  totpEnrolledAt?: T;
  totpFailedAttempts?: T;
  totpLockUntil?: T;
  resetTwoFactorDevice?: T;
  regenerateTwoFactorSecret?: T;
  tenants?:
    | T
    | {
        tenant?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  alt?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "attachments_select".
 */
export interface AttachmentsSelect<T extends boolean = true> {
  tenant?: T;
  alt?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "sites_select".
 */
export interface SitesSelect<T extends boolean = true> {
  siteId?: T;
  name?: T;
  url?: T;
  isAdminSite?: T;
  satisfactionEnabled?: T;
  dataManagerEnabled?: T;
  memberApprovalRequired?: T;
  accessibilityValidation?: T;
  twoFactorEnabled?: T;
  accountApplicationEnabled?: T;
  logo?: T;
  footer?:
    | T
    | {
        orgName?:
          | T
          | {
              value?: T;
              show?: T;
            };
        addressPostalCode?:
          | T
          | {
              value?: T;
              show?: T;
            };
        addressLine1?:
          | T
          | {
              value?: T;
              show?: T;
            };
        addressLine2?:
          | T
          | {
              value?: T;
              show?: T;
            };
        phone?:
          | T
          | {
              value?: T;
              show?: T;
            };
        fax?:
          | T
          | {
              value?: T;
              show?: T;
            };
        copyright?:
          | T
          | {
              value?: T;
              show?: T;
            };
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "departments_select".
 */
export interface DepartmentsSelect<T extends boolean = true> {
  name?: T;
  duties?: T;
  phone?: T;
  fax?: T;
  isActive?: T;
  parent?: T;
  order?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "codeClassifications_select".
 */
export interface CodeClassificationsSelect<T extends boolean = true> {
  code?: T;
  name?: T;
  description?: T;
  isActive?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "codeGroups_select".
 */
export interface CodeGroupsSelect<T extends boolean = true> {
  codeId?: T;
  name?: T;
  classification?: T;
  description?: T;
  isActive?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "codes_select".
 */
export interface CodesSelect<T extends boolean = true> {
  group?: T;
  code?: T;
  name?: T;
  parent?: T;
  depth?: T;
  order?: T;
  description?: T;
  legacyValue?: T;
  isActive?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "boardTypes_select".
 */
export interface BoardTypesSelect<T extends boolean = true> {
  code?: T;
  name?: T;
  kind?: T;
  tableName?: T;
  description?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "boards_select".
 */
export interface BoardsSelect<T extends boolean = true> {
  tenant?: T;
  bbsId?: T;
  name?: T;
  securityDoc?: T;
  boardType?: T;
  isIntegrated?: T;
  skin?: T;
  boardForm?: T;
  sortOrder?: T;
  editorForAdminOnly?: T;
  commentsEnabled?: T;
  prevNextEnabled?: T;
  excelExport?: T;
  userPostAllowed?: T;
  secretPostAllowed?: T;
  newIconWindow?: T;
  listCount?: T;
  pageCount?: T;
  topContent?: T;
  bottomContent?: T;
  headerNotice?: T;
  attachmentsEnabled?: T;
  attachmentMaxCount?: T;
  attachmentMaxSizeMB?: T;
  attachmentAllowedExtensions?: T;
  categories?:
    | T
    | {
        classificationCode?: T;
        title?: T;
        htmlTitleAttr?: T;
        attributeValue?: T;
        style?: T;
        useFlag?: T;
        requiredFlag?: T;
        listFlag?: T;
        detailFlag?: T;
        searchFlag?: T;
        id?: T;
      };
  fields?:
    | T
    | {
        fieldKey?: T;
        label?: T;
        htmlTitleAttr?: T;
        attributeValue?: T;
        style?: T;
        inputType?: T;
        useFlag?: T;
        requiredFlag?: T;
        listFlag?: T;
        detailFlag?: T;
        searchFlag?: T;
        id?: T;
      };
  listFieldOrder?: T;
  detailFieldOrder?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "posts_select".
 */
export interface PostsSelect<T extends boolean = true> {
  tenant?: T;
  board?: T;
  boardKind?: T;
  securityDoc?: T;
  title?: T;
  author?: T;
  authorUser?: T;
  department?: T;
  team?: T;
  content?: T;
  viewCount?: T;
  isNotice?: T;
  noticeFrom?: T;
  noticeTo?: T;
  isSecret?: T;
  category1?: T;
  category2?: T;
  category3?: T;
  extraField1?: T;
  extraField2?: T;
  extraField3?: T;
  extraField4?: T;
  extraContent1?: T;
  extraContent2?: T;
  extraContent3?: T;
  extraContent4?: T;
  attachments?:
    | T
    | {
        media?: T;
        description?: T;
        isRepresentative?: T;
        fileSn?: T;
        downloadCount?: T;
        id?: T;
      };
  answer?: T;
  answeredBy?: T;
  answeredAt?: T;
  isAnswered?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "profanityWords_select".
 */
export interface ProfanityWordsSelect<T extends boolean = true> {
  word?: T;
  isActive?: T;
  registrant?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "memberBannedWords_select".
 */
export interface MemberBannedWordsSelect<T extends boolean = true> {
  word?: T;
  scope?: T;
  isActive?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "members_select".
 */
export interface MembersSelect<T extends boolean = true> {
  loginId?: T;
  name?: T;
  mobile?: T;
  status?: T;
  tenant?: T;
  marketingConsent?: T;
  termsConsents?:
    | T
    | {
        category?: T;
        version?: T;
        agreedAt?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "notificationAreas_select".
 */
export interface NotificationAreasSelect<T extends boolean = true> {
  tenant?: T;
  image?: T;
  title?: T;
  linkType?: T;
  linkInternal?: T;
  linkExternal?: T;
  newWindow?: T;
  active?: T;
  exposeFrom?: T;
  exposeTo?: T;
  displayOrder?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "popups_select".
 */
export interface PopupsSelect<T extends boolean = true> {
  tenant?: T;
  image?: T;
  title?: T;
  linkType?: T;
  linkInternal?: T;
  linkExternal?: T;
  active?: T;
  exposeFrom?: T;
  exposeTo?: T;
  width?: T;
  height?: T;
  top?: T;
  left?: T;
  showScrollbar?: T;
  closeForDay?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "banners_select".
 */
export interface BannersSelect<T extends boolean = true> {
  tenant?: T;
  image?: T;
  isRepresentative?: T;
  title?: T;
  linkType?: T;
  linkInternal?: T;
  linkExternal?: T;
  newWindow?: T;
  active?: T;
  exposeFrom?: T;
  exposeTo?: T;
  displayOrder?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "adminNotices_select".
 */
export interface AdminNoticesSelect<T extends boolean = true> {
  tenant?: T;
  noticeType?: T;
  pinFrom?: T;
  pinTo?: T;
  title?: T;
  department?: T;
  team?: T;
  author?: T;
  content?: T;
  attachments?:
    | T
    | {
        media?: T;
        description?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "guideMenus_select".
 */
export interface GuideMenusSelect<T extends boolean = true> {
  tenant?: T;
  position?: T;
  name?: T;
  linkType?: T;
  linkInternal?: T;
  linkExternal?: T;
  newWindow?: T;
  displayOrder?: T;
  active?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "menus_select".
 */
export interface MenusSelect<T extends boolean = true> {
  tenant?: T;
  name?: T;
  menuNumber?: T;
  parent?: T;
  order?: T;
  contentType?: T;
  board?: T;
  linkUrl?: T;
  newWindow?: T;
  active?: T;
  personInCharge?: T;
  exposureCondition?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "webContents_select".
 */
export interface WebContentsSelect<T extends boolean = true> {
  tenant?: T;
  menu?: T;
  name?: T;
  title?: T;
  content?: T;
  responsibleDept?: T;
  responsiblePerson?: T;
  contentUrl?: T;
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "termsDocuments_select".
 */
export interface TermsDocumentsSelect<T extends boolean = true> {
  tenant?: T;
  category?: T;
  menu?: T;
  title?: T;
  content?: T;
  effectiveDate?: T;
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "shortUrls_select".
 */
export interface ShortUrlsSelect<T extends boolean = true> {
  tenant?: T;
  linkName?: T;
  originalUrl?: T;
  remarks?: T;
  code?: T;
  hitCount?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "helpEntries_select".
 */
export interface HelpEntriesSelect<T extends boolean = true> {
  name?: T;
  parent?: T;
  order?: T;
  content?: T;
  bindType?: T;
  urlPattern?: T;
  menuNumber?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "surveys_select".
 */
export interface SurveysSelect<T extends boolean = true> {
  tenant?: T;
  title?: T;
  description?: T;
  department?: T;
  contactPhone?: T;
  topic?: T;
  openFrom?: T;
  openTo?: T;
  isActive?: T;
  status?: T;
  audience?: T;
  resultVisibility?: T;
  anonymous?: T;
  hasResponses?: T;
  startedAt?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "surveyQuestions_select".
 */
export interface SurveyQuestionsSelect<T extends boolean = true> {
  tenant?: T;
  survey?: T;
  order?: T;
  text?: T;
  type?: T;
  required?: T;
  includeInPublicResults?: T;
  options?:
    | T
    | {
        label?: T;
        value?: T;
        order?: T;
        isOther?: T;
        nextQuestionOrder?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "surveyResponses_select".
 */
export interface SurveyResponsesSelect<T extends boolean = true> {
  tenant?: T;
  survey?: T;
  respondent?: T;
  submittedAt?: T;
  participantKey?: T;
  answers?:
    | T
    | {
        question?: T;
        optionValues?: T;
        textValue?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "satisfactionRatings_select".
 */
export interface SatisfactionRatingsSelect<T extends boolean = true> {
  tenant?: T;
  menu?: T;
  pageKey?: T;
  score?: T;
  member?: T;
  submittedAt?: T;
  ipHash?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pageViews_select".
 */
export interface PageViewsSelect<T extends boolean = true> {
  tenant?: T;
  path?: T;
  menu?: T;
  deviceType?: T;
  osFamily?: T;
  browserFamily?: T;
  referrerHost?: T;
  sessionKey?: T;
  ts?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "trafficDaily_select".
 */
export interface TrafficDailySelect<T extends boolean = true> {
  tenant?: T;
  date?: T;
  totalViews?: T;
  uniqueVisitors?: T;
  byPath?: T;
  byOs?: T;
  byBrowser?: T;
  byDevice?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "roles_select".
 */
export interface RolesSelect<T extends boolean = true> {
  roleId?: T;
  name?: T;
  description?: T;
  isSuper?: T;
  menuGrants?: T;
  users?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "adminMenus_select".
 */
export interface AdminMenusSelect<T extends boolean = true> {
  menuKey?: T;
  name?: T;
  parent?: T;
  order?: T;
  collectionSlug?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "passwordPolicies_select".
 */
export interface PasswordPoliciesSelect<T extends boolean = true> {
  ruleText?: T;
  isActive?: T;
  createdBy?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "adminIpRules_select".
 */
export interface AdminIpRulesSelect<T extends boolean = true> {
  applicantName?: T;
  affiliation?: T;
  phone?: T;
  memo?: T;
  ipAddress?: T;
  accessType?: T;
  validFrom?: T;
  validTo?: T;
  isActive?: T;
  siteId?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "accessLogs_select".
 */
export interface AccessLogsSelect<T extends boolean = true> {
  actor?: T;
  actorLabel?: T;
  menuKey?: T;
  menuLabel?: T;
  action?: T;
  url?: T;
  ipAddress?: T;
  sessionLoginAt?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "loginHistory_select".
 */
export interface LoginHistorySelect<T extends boolean = true> {
  userLabel?: T;
  loginId?: T;
  success?: T;
  failReason?: T;
  ipAddress?: T;
  isOverseas?: T;
  isMobile?: T;
  userAgent?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "permissionChangeLogs_select".
 */
export interface PermissionChangeLogsSelect<T extends boolean = true> {
  targetUserLabel?: T;
  targetUserId?: T;
  targetUserEmail?: T;
  changeSummary?: T;
  actorLabel?: T;
  ipAddress?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "menuPermissionLogs_select".
 */
export interface MenuPermissionLogsSelect<T extends boolean = true> {
  roleLabel?: T;
  roleId?: T;
  addedMenus?: T;
  removedMenus?: T;
  roleMemberSnapshot?: T;
  actorLabel?: T;
  ipAddress?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "personalInfoAccessLogs_select".
 */
export interface PersonalInfoAccessLogsSelect<T extends boolean = true> {
  occurredAt?: T;
  screen?: T;
  subjectLabel?: T;
  subjectMemberId?: T;
  subjectSiteId?: T;
  url?: T;
  action?: T;
  purposeCategory?: T;
  purposeDetail?: T;
  viewerLabel?: T;
  viewerId?: T;
  ipAddress?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "errorLogs_select".
 */
export interface ErrorLogsSelect<T extends boolean = true> {
  occurredAt?: T;
  exceptionClass?: T;
  message?: T;
  url?: T;
  httpMethod?: T;
  statusCode?: T;
  actorLabel?: T;
  actorId?: T;
  ipAddress?: T;
  stackDigest?: T;
  userAgentFamily?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "collections_widget".
 */
export interface CollectionsWidget {
  data?: {
    [k: string]: unknown;
  };
  width: 'full';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}